<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
    <PackageReference Include="Antlr4BuildTasks" Version="12.14.0" />
  </ItemGroup>

  <ItemGroup>
    <Antlr4 Include="Grammar\Formula.g4">
      <Package>CalcEngine.Core.Generated</Package>
      <Visitor>true</Visitor>
      <Listener>false</Listener>
    </Antlr4>
  </ItemGroup>

</Project>
